// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: block.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block represents a block in the blockchain
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Contracts     []*Contract            `protobuf:"bytes,4,rep,name=contracts,proto3" json:"contracts,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,5,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Nonce         int32                  `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Height        int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *Block) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Block) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Block) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Transaction represents a transaction in the blockchain
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs        []*TxInput             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TxOutput            `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetInputs() []*TxInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Transaction) GetOutputs() []*TxOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// TxInput represents an input in a transaction
type TxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           int32                  `protobuf:"varint,2,opt,name=out,proto3" json:"out,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *TxInput) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TxInput) GetOut() int32 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *TxInput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TxInput) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

// TxOutput represents an output in a transaction
type TxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PubKeyHash    []byte                 `protobuf:"bytes,2,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *TxOutput) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

// TxOutputs represents a collection of transaction outputs
type TxOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*TxOutput            `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutputs) Reset() {
	*x = TxOutputs{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutputs) ProtoMessage() {}

func (x *TxOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutputs.ProtoReflect.Descriptor instead.
func (*TxOutputs) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *TxOutputs) GetOutputs() []*TxOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Contract represents a smart contract with milestones
type Contract struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Milestones     []*Milestone           `protobuf:"bytes,7,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Parties        []*Party               `protobuf:"bytes,8,rep,name=parties,proto3" json:"parties,omitempty"`
	Terms          []byte                 `protobuf:"bytes,9,opt,name=terms,proto3" json:"terms,omitempty"`
	CreatorAddress string                 `protobuf:"bytes,10,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	Attachments    [][]byte               `protobuf:"bytes,11,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *Contract) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Contract) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contract) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contract) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Contract) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Contract) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Contract) GetMilestones() []*Milestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

func (x *Contract) GetParties() []*Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *Contract) GetTerms() []byte {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *Contract) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *Contract) GetAttachments() [][]byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Milestone represents a deliverable within a contract
type Milestone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	DueDate       int64                  `protobuf:"varint,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Evidence      []byte                 `protobuf:"bytes,9,opt,name=evidence,proto3" json:"evidence,omitempty"`
	ApprovedBy    []string               `protobuf:"bytes,10,rep,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Milestone) Reset() {
	*x = Milestone{}
	mi := &file_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Milestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Milestone) ProtoMessage() {}

func (x *Milestone) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Milestone.ProtoReflect.Descriptor instead.
func (*Milestone) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{6}
}

func (x *Milestone) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Milestone) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Milestone) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Milestone) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Milestone) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *Milestone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Milestone) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Milestone) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Milestone) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Milestone) GetApprovedBy() []string {
	if x != nil {
		return x.ApprovedBy
	}
	return nil
}

// Party represents a participant in a contract
type Party struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{7}
}

func (x *Party) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Party) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Party) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Party) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ContractState wraps a contract with its milestones for storage
type ContractState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Milestones    []*Milestone           `protobuf:"bytes,2,rep,name=milestones,proto3" json:"milestones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractState) Reset() {
	*x = ContractState{}
	mi := &file_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractState) ProtoMessage() {}

func (x *ContractState) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractState.ProtoReflect.Descriptor instead.
func (*ContractState) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{8}
}

func (x *ContractState) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ContractState) GetMilestones() []*Milestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x05block\"\xeb\x01\n" +
	"\x05Block\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x126\n" +
	"\ftransactions\x18\x03 \x03(\v2\x12.block.TransactionR\ftransactions\x12-\n" +
	"\tcontracts\x18\x04 \x03(\v2\x0f.block.ContractR\tcontracts\x12\x1b\n" +
	"\tprev_hash\x18\x05 \x01(\fR\bprevHash\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x05R\x05nonce\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\"p\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0e.block.TxInputR\x06inputs\x12)\n" +
	"\aoutputs\x18\x03 \x03(\v2\x0f.block.TxOutputR\aoutputs\"b\n" +
	"\aTxInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x10\n" +
	"\x03out\x18\x02 \x01(\x05R\x03out\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x17\n" +
	"\apub_key\x18\x04 \x01(\fR\x06pubKey\"B\n" +
	"\bTxOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12 \n" +
	"\fpub_key_hash\x18\x02 \x01(\fR\n" +
	"pubKeyHash\"6\n" +
	"\tTxOutputs\x12)\n" +
	"\aoutputs\x18\x01 \x03(\v2\x0f.block.TxOutputR\aoutputs\"\xe3\x02\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x120\n" +
	"\n" +
	"milestones\x18\a \x03(\v2\x10.block.MilestoneR\n" +
	"milestones\x12&\n" +
	"\aparties\x18\b \x03(\v2\f.block.PartyR\aparties\x12\x14\n" +
	"\x05terms\x18\t \x01(\fR\x05terms\x12'\n" +
	"\x0fcreator_address\x18\n" +
	" \x01(\tR\x0ecreatorAddress\x12 \n" +
	"\vattachments\x18\v \x03(\fR\vattachments\"\x9b\x02\n" +
	"\tMilestone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\x03R\adueDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\x12\x1a\n" +
	"\bevidence\x18\t \x01(\fR\bevidence\x12\x1f\n" +
	"\vapproved_by\x18\n" +
	" \x03(\tR\n" +
	"approvedBy\"r\n" +
	"\x05Party\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"n\n" +
	"\rContractState\x12+\n" +
	"\bcontract\x18\x01 \x01(\v2\x0f.block.ContractR\bcontract\x120\n" +
	"\n" +
	"milestones\x18\x02 \x03(\v2\x10.block.MilestoneR\n" +
	"milestonesB1Z/github.com/codila125/foedus-blockchain/protobufb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_block_proto_goTypes = []any{
	(*Block)(nil),         // 0: block.Block
	(*Transaction)(nil),   // 1: block.Transaction
	(*TxInput)(nil),       // 2: block.TxInput
	(*TxOutput)(nil),      // 3: block.TxOutput
	(*TxOutputs)(nil),     // 4: block.TxOutputs
	(*Contract)(nil),      // 5: block.Contract
	(*Milestone)(nil),     // 6: block.Milestone
	(*Party)(nil),         // 7: block.Party
	(*ContractState)(nil), // 8: block.ContractState
}
var file_block_proto_depIdxs = []int32{
	1, // 0: block.Block.transactions:type_name -> block.Transaction
	5, // 1: block.Block.contracts:type_name -> block.Contract
	2, // 2: block.Transaction.inputs:type_name -> block.TxInput
	3, // 3: block.Transaction.outputs:type_name -> block.TxOutput
	3, // 4: block.TxOutputs.outputs:type_name -> block.TxOutput
	6, // 5: block.Contract.milestones:type_name -> block.Milestone
	7, // 6: block.Contract.parties:type_name -> block.Party
	5, // 7: block.ContractState.contract:type_name -> block.Contract
	6, // 8: block.ContractState.milestones:type_name -> block.Milestone
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
