// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: core.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractCore represents the immutable core of a contract for ID generation
type ContractCore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Milestones     []*MilestoneCore       `protobuf:"bytes,4,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Parties        []*PartyCoreData       `protobuf:"bytes,5,rep,name=parties,proto3" json:"parties,omitempty"`
	Terms          []byte                 `protobuf:"bytes,6,opt,name=terms,proto3" json:"terms,omitempty"`
	CreatorAddress string                 `protobuf:"bytes,7,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	Attachments    [][]byte               `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractCore) Reset() {
	*x = ContractCore{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCore) ProtoMessage() {}

func (x *ContractCore) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCore.ProtoReflect.Descriptor instead.
func (*ContractCore) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *ContractCore) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContractCore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContractCore) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ContractCore) GetMilestones() []*MilestoneCore {
	if x != nil {
		return x.Milestones
	}
	return nil
}

func (x *ContractCore) GetParties() []*PartyCoreData {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *ContractCore) GetTerms() []byte {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *ContractCore) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *ContractCore) GetAttachments() [][]byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// MilestoneCore represents the immutable parts of a milestone
type MilestoneCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MilestoneCore) Reset() {
	*x = MilestoneCore{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilestoneCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneCore) ProtoMessage() {}

func (x *MilestoneCore) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneCore.ProtoReflect.Descriptor instead.
func (*MilestoneCore) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *MilestoneCore) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MilestoneCore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MilestoneCore) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MilestoneCore) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// PartyCoreData represents the immutable parts of a Party
type PartyCoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyCoreData) Reset() {
	*x = PartyCoreData{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyCoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyCoreData) ProtoMessage() {}

func (x *PartyCoreData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyCoreData.ProtoReflect.Descriptor instead.
func (*PartyCoreData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *PartyCoreData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PartyCoreData) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PartyCoreData) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"\xaa\x02\n" +
	"\fContractCore\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x123\n" +
	"\n" +
	"milestones\x18\x04 \x03(\v2\x13.core.MilestoneCoreR\n" +
	"milestones\x12-\n" +
	"\aparties\x18\x05 \x03(\v2\x13.core.PartyCoreDataR\aparties\x12\x14\n" +
	"\x05terms\x18\x06 \x01(\fR\x05terms\x12'\n" +
	"\x0fcreator_address\x18\a \x01(\tR\x0ecreatorAddress\x12 \n" +
	"\vattachments\x18\b \x03(\fR\vattachments\"|\n" +
	"\rMilestoneCore\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\\\n" +
	"\rPartyCoreData\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKeyB1Z/github.com/codila125/foedus-blockchain/protobufb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_proto_goTypes = []any{
	(*ContractCore)(nil),  // 0: core.ContractCore
	(*MilestoneCore)(nil), // 1: core.MilestoneCore
	(*PartyCoreData)(nil), // 2: core.PartyCoreData
}
var file_core_proto_depIdxs = []int32{
	1, // 0: core.ContractCore.milestones:type_name -> core.MilestoneCore
	2, // 1: core.ContractCore.parties:type_name -> core.PartyCoreData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
