// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: network.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeightData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeightData) Reset() {
	*x = HeightData{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeightData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightData) ProtoMessage() {}

func (x *HeightData) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightData.ProtoReflect.Descriptor instead.
func (*HeightData) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *HeightData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type VersionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	LastHash      []byte                 `protobuf:"bytes,2,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionData) Reset() {
	*x = VersionData{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionData) ProtoMessage() {}

func (x *VersionData) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionData.ProtoReflect.Descriptor instead.
func (*VersionData) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *VersionData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VersionData) GetLastHash() []byte {
	if x != nil {
		return x.LastHash
	}
	return nil
}

func (x *VersionData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type BlockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *BlockData) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BlockData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\anetwork\"$\n" +
	"\n" +
	"HeightData\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\"[\n" +
	"\vVersionData\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x1b\n" +
	"\tlast_hash\x18\x02 \x01(\fR\blastHash\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"e\n" +
	"\tBlockData\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB1Z/github.com/codila125/foedus-blockchain/protobufb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_network_proto_goTypes = []any{
	(*HeightData)(nil),  // 0: network.HeightData
	(*VersionData)(nil), // 1: network.VersionData
	(*BlockData)(nil),   // 2: network.BlockData
}
var file_network_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
